[LightMode]
# 覆盖默认值
OverrideDefault=True
# 高亮颜色
HighlightColor=#faf7f0
# 悬停时高亮颜色
HighlightHoverColor=#f5f0e1
# 高亮文本颜色
HighlightTextColor=#000000
# 按下时高亮文本颜色
HighlightTextPressColor=#7f7f7f
# 高亮标签颜色
HighlightLabelColor=#d4af37
# 高亮注释颜色
HighlightCommentColor=#bfa030
# 高亮标记颜色
HighlightMarkColor=#d4af37
# 面板颜色
PanelColor=#ffffff
# 文本颜色
TextColor=#2b2b2b
# 标签颜色
LabelColor=#888888
# 注释颜色
CommentColor=#aaaaaa
# 翻页按钮颜色
PagingButtonColor=#888888
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#e0e0e0
# 指示文本颜色
AuxColor=#2b2b2b
# 光标前的预编辑颜色
PreeditColorPreCaret=#d4af37
# 预编辑光标颜色
PreeditColorCaret=#000000
# 光标后的预编辑颜色
PreeditColorPostCaret=#2b2b2b
# 边框颜色
BorderColor=#ebebeb
# 分隔线颜色
DividerColor=#faf7f0

[DarkMode]
# 覆盖默认值
OverrideDefault=True
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#262626
# 悬停时高亮颜色
HighlightHoverColor=#333333
# 高亮文本颜色
HighlightTextColor=#d4af37
# 按下时高亮文本颜色
HighlightTextPressColor=#f7e7ce
# 高亮标签颜色
HighlightLabelColor=#c5a059
# 高亮注释颜色
HighlightCommentColor=#8c7335
# 高亮标记颜色
HighlightMarkColor=#d4af37
# 面板颜色
PanelColor=#121212
# 文本颜色
TextColor=#e0e0e0
# 标签颜色
LabelColor=#555555
# 注释颜色
CommentColor=#444444
# 翻页按钮颜色
PagingButtonColor=#d4af37
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#333333
# 指示文本颜色
AuxColor=#e0e0e0
# 光标前的预编辑颜色
PreeditColorPreCaret=#d4af37
# 预编辑光标颜色
PreeditColorCaret=#f7e7ce
# 光标后的预编辑颜色
PreeditColorPostCaret=#e0e0e0
# 边框颜色
BorderColor=#333333
# 分隔线颜色
DividerColor=#262626

[Typography]
# 布局
Layout=Horizontal
# 书写模式
WritingMode="Horizontal top-bottom"
# 垂直时注释右对齐
VerticalCommentsAlignRight=False
# 翻页按钮样式
PagingButtonsStyle=Arrow

[Background]
# 图片
ImageUrl=
# 有图片时保留面板颜色
KeepPanelColorWhenHasImage=False
# 模糊
Blur=System
# 阴影
Shadow=True

[Font]
# 文本字号
TextFontSize=17
# 文本字重
TextFontWeight=400
# 标签字号
LabelFontSize=14
# 标签字重
LabelFontWeight=400
# 注释字号
CommentFontSize=12
# 注释字重
CommentFontWeight=400
# 预编辑字号
PreeditFontSize=17
# 预编辑字重
PreeditFontWeight=400

[Caret]
# 样式
Style=Blink
# 文本
Text=‸

[Highlight]
# 标记样式
MarkStyle=None
# 标记文本
MarkText=🐧
# 悬停行为
HoverBehavior=None

[Size]
# 覆盖默认值
OverrideDefault=True
# 边框宽度（px）
BorderWidth=1
# 边框半径（px）
BorderRadius=4
# 外边距（px）
Margin=4
# 高亮半径（px）
HighlightRadius=2
# 顶填充（px）
TopPadding=8
# 右填充（px）
RightPadding=12
# 底填充（px）
BottomPadding=8
# 左填充（px）
LeftPadding=12
# 标签、文本、注释间隔（px）
LabelTextGap=10
# 垂直时最小宽度（px）
VerticalMinWidth=180
# 卷轴单元格宽度 (px)
ScrollCellWidth=65
# 水平分隔线宽度（px）
HorizontalDividerWidth=0
