[LightMode]
# 覆盖默认值
OverrideDefault=True
# 高亮颜色
HighlightColor=#03a870
# 悬停时高亮颜色
HighlightHoverColor=#03a870
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#444444
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#ffffff
# 文本颜色
TextColor=#444444
# 标签颜色
LabelColor=#888888
# 注释颜色
CommentColor=#444444
# 翻页按钮颜色
PagingButtonColor=#686868
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#b4b4b4
# 指示文本颜色
AuxColor=#000000
# 光标前的预编辑颜色
PreeditColorPreCaret=#444444
# 预编辑光标颜色
PreeditColorCaret=#444444
# 光标后的预编辑颜色
PreeditColorPostCaret=#444444
# 边框颜色
BorderColor=#e1e1e1
# 分隔线颜色
DividerColor=#ffffff

[DarkMode]
# 覆盖默认值
OverrideDefault=True
# 与浅色模式相同
SameWithLightMode=False
# 高亮颜色
HighlightColor=#03a870
# 悬停时高亮颜色
HighlightHoverColor=#03a870
# 高亮文本颜色
HighlightTextColor=#ffffff
# 按下时高亮文本颜色
HighlightTextPressColor=#ffffff
# 高亮标签颜色
HighlightLabelColor=#ffffff
# 高亮注释颜色
HighlightCommentColor=#ffffff
# 高亮标记颜色
HighlightMarkColor=#ffffff
# 面板颜色
PanelColor=#151515
# 文本颜色
TextColor=#bbbbbb
# 标签颜色
LabelColor=#777777
# 注释颜色
CommentColor=#bbbbbb
# 翻页按钮颜色
PagingButtonColor=#979797
# 禁用的翻页按钮颜色
DisabledPagingButtonColor=#7f7f7f
# 指示文本颜色
AuxColor=#ffffff
# 光标前的预编辑颜色
PreeditColorPreCaret=#ffffff
# 预编辑光标颜色
PreeditColorCaret=#ffffff
# 光标后的预编辑颜色
PreeditColorPostCaret=#ffffff
# 边框颜色
BorderColor=#828282
# 分隔线颜色
DividerColor=#151515

[Typography]
# 布局
Layout=Horizontal
# 书写模式
WritingMode="Horizontal top-bottom"
# 垂直时注释右对齐
VerticalCommentsAlignRight=False
# 翻页按钮样式
PagingButtonsStyle=Arrow

[Background]
# 图片
ImageUrl=
# 有图片时保留面板颜色
KeepPanelColorWhenHasImage=False
# 模糊
Blur=System
# 阴影
Shadow=True

[Font]
# 文本字号
TextFontSize=16
# 文本字重
TextFontWeight=400
# 标签字号
LabelFontSize=12
# 标签字重
LabelFontWeight=400
# 注释字号
CommentFontSize=12
# 注释字重
CommentFontWeight=400
# 预编辑字号
PreeditFontSize=16
# 预编辑字重
PreeditFontWeight=400

[Caret]
# 样式
Style=Blink
# 文本
Text=‸

[Highlight]
# 标记样式
MarkStyle=None
# 标记文本
MarkText=🐧
# 悬停行为
HoverBehavior=None

[Size]
# 覆盖默认值
OverrideDefault=True
# 边框宽度（px）
BorderWidth=1
# 边框半径（px）
BorderRadius=8
# 外边距（px）
Margin=2
# 高亮半径（px）
HighlightRadius=6
# 顶填充（px）
TopPadding=1
# 右填充（px）
RightPadding=8
# 底填充（px）
BottomPadding=1
# 左填充（px）
LeftPadding=7
# 标签、文本、注释间隔（px）
LabelTextGap=4
# 垂直时最小宽度（px）
VerticalMinWidth=200
# 卷轴单元格宽度 (px)
ScrollCellWidth=65
# 水平分隔线宽度（px）
HorizontalDividerWidth=0
